### ISSUE TITLE
[Feature] Map support (mobile and WEB)

### ISSUE THREAD

**Issue by fvisticot** [AyushBherwani1998/here_maps_webservice#1]
Is it planned to display Here Map as well.
Would be awesome to have mobile and web support !

**Comment by AyushBherwani1998** [comment]
> 
> 
> Is it planned to display Here Map as well.
> Would be awesome to have mobile and web support !

Yes, we are working on a Plugin to show interactive Here Maps in Flutter. The maps provided in REST services by HERE are not interactive since they are just an image.
