### ISSUE TITLE
Assets maxResults <= 1. 

### ISSUE THREAD

**Issue by maxgmer** [AyushBherwani1998/here_maps_webservice#4]
maxResults cant be set at the moment because of assert maxResults <= 1 instead of maxResults >= 1 && maxResults <= 10

**Comment by AyushBherwani1998** [comment]
@maxgmer Thank you for bringing this to notice.

**Comment by arps18** [comment]
Would like to work on it!

**Comment by AyushBherwani1998** [comment]
@arps18 Awesome, let me know if you need any help

**Comment by AyushBherwani1998** [comment]
#5 Fixes the issue.
